services:
  treadmill-bridge:
    build: .
    container_name: treadmill-bridge
    image: pymvtreadmill:latest
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /var/run/dbus:/var/run/dbus
    # environment:
    #   - MQTT_HOST=192.168.1.100
    #   - MQTT_PORT=1883
    #   - MQTT_USERNAME=your_username
    #   - MQTT_PASSWORD=your_password
    # command:
    #   - "--mqtt-host"
    #   - "192.168.1.100"
    #   - "--mqtt-username"
    #   - "your_username"
    #   - "--mqtt-password"
    #   - "your_password"
    # Or simply override command:
    command: ["--mqtt-host", "localhost"]
